name: docs

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  docs:
    runs-on: windows-latest
    steps:
      - uses: compas-dev/compas-actions.docs@v2
        run: |
          conda install eigen=3.4 boost-cpp mpir mpfr cgal-cpp=5.5 pybind11 compas -y
          pip install -r requirements-dev.txt
          invoke docs
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          use_conda: true
      